### ISSUE TITLE
Redeploy fib service configs in configuration training

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/workshops#10]
When we tear down Grey Matter in the [Consul](https://github.com/DecipherNow/workshops/blob/master/training/4.%20Grey%20Matter%20Configuration/Grey%20Matter%20Configuration%20Training.md#redeploying-grey-matter) section of configuration training, we redeploy core services, but we don't redeploy the Fib service configuration.

We should probably provide a script to quickly get folks back to the original deployment.

**Comment by danielpcox** [comment]
For the benefit of whoever fixes this issue, here's exactly what we're currently missing after we reinstall Grey Matter in the Consul section to make Fibonacci work again:

https://gist.github.com/kaitmore/fd60e2b6bb7fa44a87c8c5e32fb1d4a6
