### ISSUE TITLE
Remove references to k8s_use_voyager_ingress

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/workshops#18]
The latest helm charts no longer use the `k8s_use_voyager_ingress` value to configure Voyager; instead [greymatter.yaml](https://github.com/DecipherNow/helm-charts/blob/release-2.1/greymatter.yaml#L716-L761) configures the ingress type and annotations explicitly. Voyager should now work out of the box without setting any extra values.

See the following PRs for more information:

- https://github.com/DecipherNow/helm-charts/pull/435
- https://github.com/DecipherNow/helm-charts/pull/434
- https://github.com/DecipherNow/helm-charts/pull/428

**Comment by danielpcox** [comment]
That was fast.
