### ISSUE TITLE
Flat File service discovery section insufficiently clear

### ISSUE THREAD

**Issue by danielpcox** [DecipherNow/workshops#28]
The Flat File section under service discovery seems likely to be unclear, at least in what you should expect to see, how long to wait, etc.

For instance, when you actually do the delete and re-apply of Control's config, there are two Control pods. One is Terminating, so you don't want that one, but we don't say that in the text.

It's also very likely that if you're too quick to do the `kubectl cp` that control won't be up, and the file copy will fail. We should say in that case that you should just retry until it works.

We should also tell them to _follow_ the logs after that, not just view the logs, and tell them that the logs won't show anything until the 30 seconds is up and control actually tries to start.

Finally, it would be handy to also tell them that if things went wrong, you'll get an error in those logs and it's likely a problem with the control.yaml.

**Comment by zoemccormick** [comment]
closed with #41 (hopefully)
