### ISSUE TITLE
AWS creds for S3 bucket broken

### ISSUE THREAD

**Issue by danielpcox** [DecipherNow/workshops#36]
When we generate fresh credentials for Data to use in manipulating files in S3, we invariably do it wrong, and Data emits "upload into storage failed". Investigate.

Relevant `gm-integrity` test results:

```
 3.  JSONError
                     Unexpected token 'u' at 1:1
                     upload into storage failed: AccessDenied: Access Denied
                     ^
                     at test-script
                     inside "Data / Data 06 - Upload a file"

 4.  AssertionError  Listing contains file
                     expected undefined to be one of []
                     at assertion:0 in test-script
                     inside "Data / Data 08 - List my homedir"

 5.  AssertionError  Status code is 200
                     expected response to have status code 200 but got 400
                     at assertion:0 in test-script
                     inside "Data / Data 09 - Delete the file"
```

**Comment by danielpcox** [comment]
If we give the credentials _complete_ access to the S3 bucket, it works. So we're probably just missing some non-obvious necessary permission.

**Comment by zoemccormick** [comment]
Steps I used to create the bucket:

1. Create S3 bucket, grant public access
2. Create policy, with full S3 access pointing to the created bucket
3. Create a group with the created policy as a permission
4. Create a user with programmatic access, pointing to the group^

**Comment by danielpcox** [comment]
That really _sounds_ like it should be completely fine...

**Comment by danielpcox** [comment]
This policy, applied to a group containing a user whose credentials are supplied to GM Data, works. I think what was going on before was that there's a difference between granting permissions on a bucket, and granting permissions on objects _inside_ that bucket. The first statement grants permissions necessary to put, get, and delete the `data/` object at the root, and the second statement grants permissions on everything (recursively) inside.

I was also warned that although you can combine these statements by specifying "arn:aws:s3:::decipher-training-bucket*", that would _also_ grant permissions on things with the "decipher-training-bucket" _prefix_. That's why it's broken into two.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::decipher-training-bucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::decipher-training-bucket/*"
            ]
        }
    ]
}
```

**Comment by danielpcox** [comment]
With this^ it's unnecessary to make the bucket public. I have "Block all public access" turned on.

**Comment by chrisbsmith** [comment]
FYI, this is the same policy we apply to all new S3 buckets we create for GM Data. The buckets should never be public.

**Comment by danielpcox** [comment]
Closing 'cause we understand now. (Thanks Chris)
