### ISSUE TITLE
Rework flat file section of configuration training

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/workshops#9]
During the [flat file](https://github.com/DecipherNow/workshops/blob/master/training/4.%20Grey%20Matter%20Configuration/Grey%20Matter%20Configuration%20Training.md#flat-file) portion of the service discovery training, some folks were experiencing a `Liveness probe failed` error after applying the control.yaml deployment and copying in the routes.yaml file. 

This is most likely due to the fact that we are making control wait to start up for 30s so we can copy in the routes.yaml file, but the livenessProbe is trying to connect after 5 seconds, and when it can't it puts the pod into an Error state.

**Comment by danielpcox** [comment]
Another smaller problem that falls under this issue title is the fact that I have them load the `routes.yaml` file from `/home/ubuntu/routes.yaml`, but I have them _mount in_ the file at `/tmp/routes.yaml`. Just change the load path (in Control's environment variable setting) to `/tmp/routes.yaml`.
